# Generated by Django 5.1.2 on 2024-11-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, unique_for_date='create_at'),
        ),
    ]
